### ISSUE TITLE
Count ads blocked?

### ISSUE THREAD

**Issue by anonmate** [ghostery/adblocker#2369]
Is there anyway with this package to count the amount of ads that have been blocked?

**Comment by remusao** [comment]
Hi @anonmate,

Thanks for reaching out. Certainly there is, the blocker interface exposes a bunch of events that you can listen to. You can check this for an example: https://github.com/ghostery/adblocker/blob/master/packages/adblocker-electron-example/index.ts#L43

It's fairly granular and does not expose an "ads-blocked" event, because in practice it's very hard to define what an "ad" is. But it's pretty straightforward to count how many network requests were blocked (which is what most adblockers would display as "ads blocked").

I hope this helps,
