### ISSUE TITLE
manifest version 3

### ISSUE THREAD

**Issue by grinono** [ghostery/adblocker#2961]
Are there any implications on using this library on Chromium manifest v3.  Next year the v2 will be deprecated. So considering moving to v3 now. Is it correct that the lib works with the webRequest API. Any plans to move that over to the new API?

**Comment by remusao** [comment]
Hi @grinono,

You are right that the Manifest v3 will have implications for the Ghostery adblocker library when used in the context of web browsers. Firstly, the network filtering part is now taken care of by the declarativeNetRequest API instead of blocking webRequest; this makes this aspect of the library obsolete in this regard (and we do not provide a converter to the new format so you would likely want to rely on other projects for that). On the other hand, the cosmetic injections part can still be relevant (but might need updating to make the best use of the new APIs). Also, the blocking engine can still be useful if you'd like to use the adblocker to analyze the requests without blocking (e.g. for labeling ads/trackers).

Note that this only impact the webExtension blocker, and that the abstractions Electron, Puppeteer, Node.js and Playwright will keep working as they do currently.

I hope that helps,
