### ISSUE TITLE
Future of this project

### ISSUE THREAD

**Issue by Immortalin** [ghostery/adblocker#826]
Considering that Cliqz will be shutting down, what is the future of this?

**Comment by remusao** [comment]
Hi @Immortalin,

Thanks for reaching out. There is still a lot of uncertainty and questions will find more precise answers in the coming days (or weeks). For now, since this project is still powering Ghostery's adblocker and is also used as part of more than a hundred open-source projects on GitHub, you can expect the library to stick around for longer. Also, there is no strong dependency between `@cliqz/adblocker` and any Cliqz infrastructure (CI is using GitHub Actions and rules are hosted on GitHub), so there is no worry to have on this side either.

I'm happy to answer any other question you would have,
Best,

**Comment by gurgunday** [comment]
@remusao I'm so sorry to hear the bad news. I would write you on Twitter if I had an account there but nonetheless I want to thank Cliqz and you personally. You were so engaged with the community and it really hurts me to see that Cliqz will no longer be with us... With so much talent it really seemed like Google had a serious competitor. After all, I guess if I had completed that port to Snap and AppImage, things would be much better :)

**Comment by chrmod** [comment]
Adblocker project is maintained by Ghostery - all contributions are welcome!
